version: 0.0
os: linux
files:
  - source: ./server.zip
    destination: /tmp/
hooks:
  ApplicationStop:
    - location: ./stop.sh
      timeout: 150
      runas: ec2-user
  AfterInstall:
    - location: ./unzip.sh
      timeout: 150
      runas: ec2-user
  ApplicationStart:
    - location: ./start.sh
      timeout: 150
      runas: ec2-user